name: Build AppSync and AppInst Deb Packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install git curl ldid perl make python3 llvm openssl zip unzip dpkg
          # Usually no-op on GitHub Actions; included just in case:
          xcode-select --install || echo "Xcode Command Line Tools already installed"

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "export PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV
          # Source it so further steps inherit
          source $GITHUB_ENV

      - name: Verify Theos Installation
        run: |
          ls $HOME/theos/makefiles/common.mk  || echo "Missing common.mk"
          ls $HOME/theos/aggregate.mk        || echo "Missing aggregate.mk"

      - name: Clone AppSync repository
        run: |
          git clone https://github.com/akemin-dayo/AppSync.git

      - name: Build AppSync Unified
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH
          export SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version)

          # Disable Theos colored output:
          export DISABLE_THEOS_COLORED_OUTPUT=1

          cd AppSync
          # If you need the macros from earlier conversation:
          # ADDED_CFLAGS='-DL_LAUNCHDAEMON_PATH=\"/Library/LaunchDaemons\" -DROOT_PATH(x)=x'
          # make ARCHS="arm64 arm64e" TARGET="iphone:clang:$SDKVERSION" ADDITIONAL_CFLAGS="$ADDED_CFLAGS"
          #
          # Otherwise, just do:
          make ARCHS="arm64 arm64e" TARGET="iphone:clang:$SDKVERSION"
          make package

      - name: Upload AppSync Deb Package
        uses: actions/upload-artifact@v4
        with:
          name: appsync-deb
          path: AppSync/packages/*.deb

      - name: Build AppInst
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH
          export SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version)
          export DISABLE_THEOS_COLORED_OUTPUT=1

          cd AppSync/appinst
          make ARCHS="arm64 arm64e" TARGET="iphone:clang:$SDKVERSION"
          make package

      - name: Upload AppInst Deb Package
        uses: actions/upload-artifact@v4
        with:
          name: appinst-deb
          path: AppSync/appinst/packages/*.deb