name: Build AppSync and AppInst Deb Packages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install git curl ldid perl make python3 llvm openssl zip unzip dpkg gnu-sed automake autoconf
        xcode-select --install || echo "Xcode Command Line Tools already installed"

    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV

    - name: Clone AppSync repository
      run: |
        git clone https://github.com/akemin-dayo/AppSync.git

    - name: Clean Build
      run: |
        cd AppSync
        make clean

    - name: Build AppSync Unified
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        export SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version)
        cd AppSync
        make ARCHS="arm64 arm64e" TARGET="iphone:clang:$SDKVERSION" LOGOS_DEFAULT_DEFINES="-DNO_DEPRECATED=1"
        make package

    - name: Upload AppSync Deb Package
      uses: actions/upload-artifact@v4
      with:
        name: appsync-deb
        path: AppSync/packages/*.deb