name: Build AppSync and AppInst Deb Packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install git curl ldid perl make python3 llvm openssl zip unzip dpkg
          # Usually no-op on GitHub actions, but just in case:
          xcode-select --install || echo "Xcode Command Line Tools already installed"

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "export PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV
          # Source them so subsequent steps see them:
          source $GITHUB_ENV

      - name: Verify Theos installation
        run: |
          ls $HOME/theos/makefiles/common.mk  || echo "Missing common.mk"
          ls $HOME/theos/aggregate.mk        || echo "Missing aggregate.mk"

      - name: Clone AppSync repository
        run: |
          git clone https://github.com/akemin-dayo/AppSync.git

      - name: Build AppSync Unified
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH
          export SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version)
          
          # Disable color to avoid parentheses in shell
          export DISABLE_THEOS_COLORED_OUTPUT=1
          
          # Define macros so pkg-actions.m compiles
          export ADDED_CFLAGS='-DL_LAUNCHDAEMON_PATH=\"/Library/LaunchDaemons\" -DROOT_PATH(x)=x'

          cd AppSync
          make ARCHS="arm64 arm64e" TARGET="iphone:clang:$SDKVERSION" ADDITIONAL_CFLAGS="$ADDED_CFLAGS"
          make package

      - name: Upload AppSync Deb Package
        uses: actions/upload-artifact@v4
        with:
          name: appsync-deb
          path: AppSync/packages/*.deb

      - name: Build AppInst
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH
          export SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version)
          export DISABLE_THEOS_COLORED_OUTPUT=1
          
          # Same macros if needed (in case any code references ROOT_PATH)
          export ADDED_CFLAGS='-DL_LAUNCHDAEMON_PATH=\"/Library/LaunchDaemons\" -DROOT_PATH(x)=x'

          cd AppSync/appinst
          make ARCHS="arm64 arm64e" TARGET="iphone:clang:$SDKVERSION" ADDITIONAL_CFLAGS="$ADDED_CFLAGS"
          make package

      - name: Upload AppInst Deb Package
        uses: actions/upload-artifact@v4
        with:
          name: appinst-deb
          path: AppSync/appinst/packages/*.deb